version: "3.2"

services:
  terraform:
    image: terraform-local:latest
    user: ${USER_ID}:${GROUP_ID}
    userns_mode: host
    build:
      context: terraform-container
      dockerfile: Dockerfile
      args:
        TF_VERSION: 1.0.9
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_DEFAULT_REGION:
      AWS_SHARED_CREDENTIALS_FILE: /creds/.aws/credentials
      TF_LOG:
    working_dir: /app
    volumes:
      - ./terraform:/app
      - ~/.aws:/creds/.aws
      - ../app/zips:/zips
      - ../app/src/tests/test-files:/test-files
